name: CI/CD Pipeline

# 1. Trigger
on:
  push:
     branches: [ "main" ]

# 2. Runner
jobs:
  build-and-push:
    runs-on: ubuntu-latest

# 3.
    steps:

      # Download code ---> GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ehsansetaregan/startberlin-v1:latest
